#ifndef COMPWOLF_GRAPHICS_PRIVATE_VULKAN_TYPES_HEADER
#define COMPWOLF_GRAPHICS_PRIVATE_VULKAN_TYPES_HEADER

namespace CompWolf::Graphics::Private
{
	struct glfw_window {};
}

#endif // ! COMPWOLF_GRAPHICS_PRIVATE_VULKAN_TYPES_HEADER
