import "@/styles/globals.css"
import Link from "next/link";
import { getOverview } from "@/lib/api/Entity";
import MenuTree from "../lib/MenuTree";
import { Reference } from "../lib/CodeComponents";

export const dynamic = 'force-static'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function HeaderMenu() {
    const overview = await getOverview()
    const data = {
        items: [
            {
                Display: ({ }) => <Link href="/">Home</Link>,
            },
            {
                Display: ({ }) => <Link href="/tutorial/">Tutorial</Link>,
            },
            {
                name: `api`,
                items: overview.projects.map(project => {
                    return {
                        name: project.name,
                        items: project.headers.map(header => {
                            return {
                                name: header.name,
                                items: header.entities.map(entity => {
                                    return {
                                        name: entity.name,
                                    }
                                }),
                            }
                        }),
                        Display: ({ children, path }) => Reference({
                            path: `${path}`,
                            children: children,
                        }),
                    }
                }),
                Display: ({ }) => <Link href="/api/">API</Link>,
            }
        ],
        pathPrefix: `/`,
    }

    return MenuTree(data)
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <HeaderMenu />
                {children}
            </body>
        </html>
    );
}
