import "@/styles/globals.css"
import Link from "next/link";

export const dynamic = 'force-static'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Link href="/">Home</Link>
                {children}
            </body>
        </html>
    );
}
